name: qa_dashboard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  frontend:
    path: ../../WHS-tours/frontend
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  url_launcher: ^6.3.0
  file_picker: ^10.0.0
  pdf: ^3.10.0
  printing: ^5.10.0
  archive: ^3.4.0
  path_provider: ^2.1.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/vlotter_logo.png
    - assets/images/vlotter_logo_white.png
    - assets/images/menu.png
    - ../../WHS-tours/frontend/assets/vlotter-logo.png
    - ../../WHS-tours/frontend/assets/images/warehouse_background.png
    - ../../WHS-tours/frontend/assets/images/main_background.png
