http:
  routers:
    dashboard:
      rule: "Host(`traefik.vlotterqa.tech`)"
      service: api@internal
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      middlewares:
        - dashboard-auth
      priority: 100

    frontend:
      rule: "Host(`vlotterqa.tech`) || Host(`www.vlotterqa.tech`)"
      service: frontend
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      priority: 10

    backend:
      rule: "(Host(`vlotterqa.tech`) || Host(`www.vlotterqa.tech`)) && (PathPrefix(`/auth`) || PathPrefix(`/users`) || PathPrefix(`/departments`) || PathPrefix(`/locations`) || PathPrefix(`/branches`) || PathPrefix(`/ova`) || PathPrefix(`/accounts`) || PathPrefix(`/jap`) || PathPrefix(`/gpp`) || PathPrefix(`/domain`) || PathPrefix(`/executor`) || PathPrefix(`/notifications`) || PathPrefix(`/notification-settings`) || PathPrefix(`/maintenance-inspections`))"
      service: backend
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      priority: 100

    whs-backend:
      rule: "(Host(`vlotterqa.tech`) || Host(`www.vlotterqa.tech`)) && (PathPrefix(`/api/rapport`) || PathPrefix(`/api/melding`) || PathPrefix(`/api/locatie`) || PathPrefix(`/api/vestiging`) || PathPrefix(`/api/probleem`) || PathPrefix(`/api/vraag`) || PathPrefix(`/api/afdeling`) || PathPrefix(`/api/domein`) || PathPrefix(`/api/probleem_opmerking`) || PathPrefix(`/api/gebruikers`))"
      service: whs
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      priority: 100

  middlewares:
    dashboard-auth:
      basicAuth:
        users:
          - "admin:$apr1$qTfH/uji$e5qDZy.BuGzftSLe99QIw1"

  services:
    frontend:
      loadBalancer:
        servers:
          - url: "http://qa-frontend:80"

    backend:
      loadBalancer:
        servers:
          - url: "http://qa-login-backend:3001"
    whs:
      loadBalancer:
        servers:
          - url: "http://qa-whs-backend:8080"